import React from "react";
import { Inter } from "next/font/google";
import StyledComponentsRegistry from "@/lib/AntdRegistry";

import AntdThemeWrapper from "@/components/AntdThemeWrapper/AntdThemeWrapper";
import ThemeContext from "@/context/ThemeContext";

import "@/styles/styles.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => (
  <ThemeContext>
    <AntdThemeWrapper>
      <html lang="en">
        <body className={inter.className}>
          <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
        </body>
      </html>
    </AntdThemeWrapper>
  </ThemeContext>
);

export default RootLayout;
